const items = [
  {
    kind: 'youtube#video',
    etag: 'M2dS_JMytZEdP8CUTpS4YcX18gM',
    id: '0NzlbBmkM3E',
    snippet: {
      publishedAt: '2022-05-05T16:00:12Z',
      channelId: 'UCHE7rAi1Fw1CBmQXFtvJmrw',
      title: 'A$AP Rocky - D.M.B. (Official Video)',
      description:
        'A$AP ROCKY’S “D.M.B.”: https://AsapRocky.lnk.to/DMB\n\nOFFICIAL VIDEO FOR ”D.M.B.” BY A$AP ROCKY\nLISTEN TO A$AP ROCKY: https://AsapRocky.lnk.to/listenYD\n\nFOLLOW A$AP ROCKY:\nFACEBOOK: https://AsapRocky.lnk.to/followFI\nINSTAGRAM: https://AsapRocky.lnk.to/followII\nTWITTER: https://AsapRocky.lnk.to/followTI\nWEBSITE: https://AsapRocky.lnk.to/followWI\n\n#ASAPRocky #DMB #OfficialVideo #HipHop',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/0NzlbBmkM3E/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/0NzlbBmkM3E/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/0NzlbBmkM3E/hqdefault.jpg',
          width: 480,
          height: 360,
        },
      },
      channelTitle: 'LIVELOVEASAPVEVO',
      tags: [
        'ASAP Rocky',
        'rihanna',
        'asap rocky music',
        'asap rocky new music',
        'rih rih',
        'fenty',
        'rocky music',
        'asap rocky babushka',
        'asap rocky babushka boi',
        'asap rocky babushka boy',
        'asap rocky Rihanna perform',
        'asap rocky interview',
        'asap rocky fashion killa',
        'asap rocky peso',
        'a$ap rocky',
        'a$ap rocky fell in love with you',
        'asap rocky fell in love with you',
        'asap rocky D.M.B.',
        'asap rocky dmb',
        'ANTI',
        'kendrick lamar',
        'Vince staples',
        'schoolboy',
        'pusha',
        'Flatbush',
        'joey',
      ],
      categoryId: '10',
      liveBroadcastContent: 'none',
      localized: {
        title: 'A$AP Rocky - D.M.B. (Official Video)',
        description:
          'A$AP ROCKY’S “D.M.B.”: https://AsapRocky.lnk.to/DMB\n\nOFFICIAL VIDEO FOR ”D.M.B.” BY A$AP ROCKY\nLISTEN TO A$AP ROCKY: https://AsapRocky.lnk.to/listenYD\n\nFOLLOW A$AP ROCKY:\nFACEBOOK: https://AsapRocky.lnk.to/followFI\nINSTAGRAM: https://AsapRocky.lnk.to/followII\nTWITTER: https://AsapRocky.lnk.to/followTI\nWEBSITE: https://AsapRocky.lnk.to/followWI\n\n#ASAPRocky #DMB #OfficialVideo #HipHop',
      },
    },
    contentDetails: {
      duration: 'PT4M53S',
      dimension: '2d',
      definition: 'hd',
      caption: 'false',
      licensedContent: true,
      regionRestriction: {
        blocked: ['RU'],
      },
      contentRating: {},
      projection: 'rectangular',
    },
    statistics: {
      viewCount: '2885979',
      likeCount: '299481',
      favoriteCount: '0',
      commentCount: '14393',
    },
  },
  {
    kind: 'youtube#video',
    etag: '5yAXVKfXMZ_aS1iheHzYAoNTtLs',
    id: 'Wg86eQkdudI',
    snippet: {
      publishedAt: '2022-05-05T15:00:00Z',
      channelId: 'UCx-KWLTKlB83hDI6UKECtJQ',
      title: 'House of the Dragon | Official Teaser Trailer | HBO Max',
      description:
        'History does not remember blood. It remembers names. August 21. #HouseoftheDragon\n\nAbout HBO Max:\nHBO Max is WarnerMedia’s direct-to-consumer offering with 10,000 hours of curated premium content. HBO Max offers powerhouse programming for everyone in the home, bringing together HBO, a robust slate of new original series, key third-party licensed programs and movies, and fan favorites from WarnerMedia’s rich library including Warner Bros., New Line, DC, CNN, TNT, TBS, truTV, Turner Classic Movies, Cartoon Network, Adult Swim, Crunchyroll, Rooster Teeth, Looney Tunes and more. #HBOMax #WarnerBrosDiscovery \n\nSUBSCRIBE TO HBO MAX\nhttp://bit.ly/HBOMaxYouTube\n\nGET HBO MAX\nhttps://itsh.bo/ways-to-get\n\nMORE HBO MAX\nHBO Max: https://hbom.ax/YT \nFollow HBO Max on Instagram: http://bit.ly/HBOMaxInstagram\nFollow HBO Max on TikTok: https://hbom.ax/HBOMaxTT\nFollow HBO Max on Twitter: http://bit.ly/HBOMaxTwitter \nLike HBO Max on Facebook: http://bit.ly/HBOMaxFacebook',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/Wg86eQkdudI/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/Wg86eQkdudI/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/Wg86eQkdudI/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/Wg86eQkdudI/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/Wg86eQkdudI/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'HBO Max',
      tags: [
        'hbo',
        'hbo max',
        'hbo max movie',
        'hbo max series',
        'hbo youtube',
        'hbo max youtube',
        'hbo max trailer',
        'hbo trailer',
        'hbo video',
        'hbo max originals',
        'house of the dragon',
        'targaryens',
        'game of thrones',
        'GOT',
        'HOTD',
        'daenerys targaryen',
        'viserys targaryen',
        'Rhaenyra Targaryen',
        'princess rhaenerya',
        'targaryen dynasty',
        'dragons',
        'mother of dragons',
        'a song of ice and fire',
        'house of the dragon teaser',
        'house of the dragon hbo',
        'house of the dragon hbo max',
        'house of the dragon teaser trailer',
        'balerion',
        'meraxes',
      ],
      categoryId: '1',
      liveBroadcastContent: 'none',
      localized: {
        title: 'House of the Dragon | Official Teaser Trailer | HBO Max',
        description:
          'History does not remember blood. It remembers names. August 21. #HouseoftheDragon\n\nAbout HBO Max:\nHBO Max is WarnerMedia’s direct-to-consumer offering with 10,000 hours of curated premium content. HBO Max offers powerhouse programming for everyone in the home, bringing together HBO, a robust slate of new original series, key third-party licensed programs and movies, and fan favorites from WarnerMedia’s rich library including Warner Bros., New Line, DC, CNN, TNT, TBS, truTV, Turner Classic Movies, Cartoon Network, Adult Swim, Crunchyroll, Rooster Teeth, Looney Tunes and more. #HBOMax #WarnerBrosDiscovery \n\nSUBSCRIBE TO HBO MAX\nhttp://bit.ly/HBOMaxYouTube\n\nGET HBO MAX\nhttps://itsh.bo/ways-to-get\n\nMORE HBO MAX\nHBO Max: https://hbom.ax/YT \nFollow HBO Max on Instagram: http://bit.ly/HBOMaxInstagram\nFollow HBO Max on TikTok: https://hbom.ax/HBOMaxTT\nFollow HBO Max on Twitter: http://bit.ly/HBOMaxTwitter \nLike HBO Max on Facebook: http://bit.ly/HBOMaxFacebook',
      },
      defaultAudioLanguage: 'en',
    },
    contentDetails: {
      duration: 'PT1M44S',
      dimension: '2d',
      definition: 'hd',
      caption: 'true',
      licensedContent: true,
      contentRating: {},
      projection: 'rectangular',
    },
    statistics: {
      viewCount: '4340071',
      likeCount: '78175',
      favoriteCount: '0',
      commentCount: '5569',
    },
  },
  {
    kind: 'youtube#video',
    etag: '1-DVwU3hB-Gg0vR7q2yHhzupy6o',
    id: 'rP09GUQFDFk',
    snippet: {
      publishedAt: '2022-05-05T16:00:26Z',
      channelId: 'UCFNosi99Sp0_eLilBiXmmXA',
      title: 'Future - WAIT FOR U (Official Music Video) ft. Drake, Tems',
      description:
        'Future feat. Drake & Tems - WAIT FOR U (Official Music Video)\n\n"I NEVER LIKED YOU" available at: https://future.lnk.to/I_NEVER_LIKED_YOU\n\nFollow Future:\nhttps://www.facebook.com/FutureOfficial\nhttps://twitter.com/1future\nhttps://www.instagram.com/future/\nhttps://www.youtube.com/user/officialfuturevideos/featured\n\nDirected by Director X\nProduced by Taj Critchlow\n\n(C) & (P) 2022 Epic Records, a division of Sony Music Entertainment. With Freebandz.\n\n#Future #Drake #Tems #WAITFORU',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/rP09GUQFDFk/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/rP09GUQFDFk/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/rP09GUQFDFk/hqdefault.jpg',
          width: 480,
          height: 360,
        },
      },
      channelTitle: 'FutureVEVO',
      tags: [
        'future',
        'kevin samuels',
        'healing together',
        'worst day',
        'future worst day',
        'worst day future',
        'healing together future',
        'future healing together',
        'future keving samuels',
        'kevin samuels future',
        'young thug',
        'chainz',
        'chief keef',
        'yo gotti',
        'meek mill',
        'nav',
        'gucci mane',
        'french montana',
        'quavo',
        '21 savage',
        'migos',
        'future never liked you',
        'never liked you future',
        'future drake tems',
        'tems drake future',
        'drake',
        'tems',
        'future drake',
        'drake future',
        'drake tems',
      ],
      categoryId: '10',
      liveBroadcastContent: 'none',
      localized: {
        title: 'Future - WAIT FOR U (Official Music Video) ft. Drake, Tems',
        description:
          'Future feat. Drake & Tems - WAIT FOR U (Official Music Video)\n\n"I NEVER LIKED YOU" available at: https://future.lnk.to/I_NEVER_LIKED_YOU\n\nFollow Future:\nhttps://www.facebook.com/FutureOfficial\nhttps://twitter.com/1future\nhttps://www.instagram.com/future/\nhttps://www.youtube.com/user/officialfuturevideos/featured\n\nDirected by Director X\nProduced by Taj Critchlow\n\n(C) & (P) 2022 Epic Records, a division of Sony Music Entertainment. With Freebandz.\n\n#Future #Drake #Tems #WAITFORU',
      },
    },
    contentDetails: {
      duration: 'PT3M59S',
      dimension: '2d',
      definition: 'hd',
      caption: 'false',
      licensedContent: true,
      regionRestriction: {
        blocked: ['RU'],
      },
      contentRating: {},
      projection: 'rectangular',
    },
    statistics: {
      viewCount: '1907328',
      likeCount: '116364',
      favoriteCount: '0',
      commentCount: '8580',
    },
  },
  {
    kind: 'youtube#video',
    etag: 'NFwfXe-jbwDClN5ociaC7WfuWpQ',
    id: '3Yh_6_zItPU',
    snippet: {
      publishedAt: '2022-05-04T12:46:12Z',
      channelId: 'UCZGYJFUizSax-yElQaFDp5Q',
      title: 'Obi-Wan Kenobi | Official Trailer | Disney+',
      description:
        'The story begins 10 years after the dramatic events of “Star Wars: Revenge of the Sith” where Obi-Wan Kenobi faced his greatest defeat—the downfall and corruption of his best friend and Jedi apprentice, Anakin Skywalker, who turned to the dark side as evil Sith Lord Darth Vader.\nThe series stars Ewan McGregor, reprising his role as the iconic Jedi Master, and also marks the return of Hayden Christensen in the role of Darth Vader. Joining the cast are Moses Ingram, Joel Edgerton, Bonnie Piesse, Kumail Nanjiani, Indira Varma, Rupert Friend, O’Shea Jackson Jr., Sung Kang, Simone Kessell and Benny Safdie.\n“Obi-Wan Kenobi” is directed by Deborah Chow and executive-produced by Kathleen Kennedy, Michelle Rejwan, Deborah Chow, Ewan McGregor and Joby Harold.',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/3Yh_6_zItPU/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/3Yh_6_zItPU/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/3Yh_6_zItPU/hqdefault.jpg',
          width: 480,
          height: 360,
        },
      },
      channelTitle: 'Star Wars',
      categoryId: '24',
      liveBroadcastContent: 'none',
      localized: {
        title: 'Obi-Wan Kenobi | Official Trailer | Disney+',
        description:
          'The story begins 10 years after the dramatic events of “Star Wars: Revenge of the Sith” where Obi-Wan Kenobi faced his greatest defeat—the downfall and corruption of his best friend and Jedi apprentice, Anakin Skywalker, who turned to the dark side as evil Sith Lord Darth Vader.\nThe series stars Ewan McGregor, reprising his role as the iconic Jedi Master, and also marks the return of Hayden Christensen in the role of Darth Vader. Joining the cast are Moses Ingram, Joel Edgerton, Bonnie Piesse, Kumail Nanjiani, Indira Varma, Rupert Friend, O’Shea Jackson Jr., Sung Kang, Simone Kessell and Benny Safdie.\n“Obi-Wan Kenobi” is directed by Deborah Chow and executive-produced by Kathleen Kennedy, Michelle Rejwan, Deborah Chow, Ewan McGregor and Joby Harold.',
      },
      defaultAudioLanguage: 'en-US',
    },
    contentDetails: {
      duration: 'PT1M29S',
      dimension: '2d',
      definition: 'hd',
      caption: 'false',
      licensedContent: true,
      contentRating: {},
      projection: 'rectangular',
    },
    statistics: {
      viewCount: '7461008',
      likeCount: '325622',
      favoriteCount: '0',
      commentCount: '17714',
    },
  },
  {
    kind: 'youtube#video',
    etag: 'mQ6iPpGQL9IICWhtP6dXFJ6pj9c',
    id: '3o8w042VdOk',
    snippet: {
      publishedAt: '2022-05-04T21:56:30Z',
      channelId: 'UCET00YnetHT7tOpu12v8jxg',
      title:
        'Real Madrid vs. Manchester City: Extended Highlights | UCL Semi-Finals - Leg 2 | CBS Sports Golazo',
      description:
        'Extended Highlights, Presented By Heineken\n\nThe first leg of Real Madrid vs. Manchester City was an instant classic. Will the scintillating Karim Benzema and Real Madrid overcome their 4-3 deficit?\n\nStream every UEFA Champions League match live on Paramount+:\nhttps://www.paramountplus.com/shows/uefa-champions-league/\n \n#UCL #ChampionsLeague #UEFA #RealMadrid #ManchesterCity',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/3o8w042VdOk/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/3o8w042VdOk/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/3o8w042VdOk/hqdefault.jpg',
          width: 480,
          height: 360,
        },
      },
      channelTitle: 'CBS Sports Golazo',
      tags: [
        'Manchester City',
        'Real Madrid',
        'Real Madrid vs. Manchester City',
      ],
      categoryId: '17',
      liveBroadcastContent: 'none',
      localized: {
        title:
          'Real Madrid vs. Manchester City: Extended Highlights | UCL Semi-Finals - Leg 2 | CBS Sports Golazo',
        description:
          'Extended Highlights, Presented By Heineken\n\nThe first leg of Real Madrid vs. Manchester City was an instant classic. Will the scintillating Karim Benzema and Real Madrid overcome their 4-3 deficit?\n\nStream every UEFA Champions League match live on Paramount+:\nhttps://www.paramountplus.com/shows/uefa-champions-league/\n \n#UCL #ChampionsLeague #UEFA #RealMadrid #ManchesterCity',
      },
    },
    contentDetails: {
      duration: 'PT16M10S',
      dimension: '2d',
      definition: 'hd',
      caption: 'true',
      licensedContent: true,
      regionRestriction: {
        allowed: ['US'],
      },
      contentRating: {},
      projection: 'rectangular',
    },
    statistics: {
      viewCount: '2214378',
      likeCount: '27173',
      favoriteCount: '0',
      commentCount: '3981',
    },
  },
]

export default items